function CombinedreversalsfluorescenceFimXPilG = import_reversal_dynamics(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COMBINEDREVERSALSFLUORESCENCEFIMXPILG = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  COMBINEDREVERSALSFLUORESCENCEFIMXPILG = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CombinedreversalsfluorescenceFimXPilG = importfile("Z:\Iscia_WS\PersatLAb-master\Graphs\Reversal_dynamics\Combined_reversals_fluorescence_FimX_PilG.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Apr-2021 16:28:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Strain", "Date", "Time", "Intervals", "Movie", "Cell", "Go", "Swap1", "Tau", "Taus", "Keep", "Comments"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Comments", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Comments", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Strain", "Time"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Strain", "Time"], "ThousandsSeparator", ",");

% Import the data
CombinedreversalsfluorescenceFimXPilG = readtable(filename, opts);

end